name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DVC pipeline
        run: |
          pip install dvc[s3]
          dvc repro --force

      - name: Build & push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/algoquant-backtester:latest .
          docker push ${{ secrets.DOCKER_REGISTRY }}/algoquant-backtester:latest

      - name: Terraform Init & Apply
        working-directory: terraform
        run: |
          terraform init -input=false
          terraform plan -out=tfplan -input=false
          terraform apply -input=false tfplan

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy Helm chart
        run: |
          helm upgrade --install algoquant-backtester helm/algoquant-backtester \
            --namespace default \
            --set image.repository=${{ secrets.DOCKER_REGISTRY }}/algoquant-backtester,image.tag=latest

      - name: Smoke Test API
        run: |
          curl --fail http://$(kubectl get svc algoquant-backtester -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'):80/healthz


mkdir -p .github/workflows
git add .github/workflows/deploy.yml
git commit -m "Add CD workflow: Terraform, Docker build & push, Helm deploy, smoke test"
git push
